In [10]:
import numpy as np
import pandas as pd

In [2]:
def compare(fitness_a, fitness_b):
    # if a dominates b, return will be 1, -1 if the contrary
    # if there is no dominance, 0 will be returned
    try:
        m = (fitness_a[0] - fitness_b[0]) / (fitness_a[1] - fitness_b[1])
    except ZeroDivisionError:
        return 0
    if m > 0:
        if fitness_a[0] < fitness_b[0]:
            return 1
        return -1
    return 0


In [3]:
def get_parents(parent_F:list):
	levels  = np.array(parent_F)[:, 2]
	max_idx = np.argmin(levels)
	return parent_F[max_idx]

In [4]:
def mix_parents(parent_a:list, parent_b:list, ratio:float = 0.5, get_indexes:bool=False):
	genotype_len = len(parent_a)

	a_idxs = set()
	acum = 0
	for i in range(genotype_len):
		acum += ratio
		if acum >= 1:
			acum -= 1
			a_idxs.add(i)
	b_idxs = {i for i in range(genotype_len)} - a_idxs

	a_idxs = list(a_idxs)
	b_idxs = list(b_idxs)
	child  = np.zeros((genotype_len), bool)

	child[a_idxs] = parent_a[a_idxs].copy()
	child[b_idxs] = parent_b[b_idxs].copy()
	if get_indexes:
		return child, (a_idxs, b_idxs)
	return child

In [5]:
def NSGA2(fitness):
    n = len(fitness)
    levels = np.zeros(n)
    dominates = [[] for _ in range(n)]
    is_dominated_by = {}
    for i in range(n):
        is_dominated_by[i] = 0
    for idx_first_point, first_point in enumerate(fitness):
        for idx_second_point in range(idx_first_point+1, len(fitness)):
            second_point = fitness[idx_second_point]
            m = compare(first_point, second_point)
            if m == 1: #first_point dominates
                is_dominated_by[idx_second_point] = is_dominated_by.get(idx_second_point, 0) + 1
                dominates[idx_first_point].append(idx_second_point)
            elif m == -1:
                is_dominated_by[idx_first_point] = is_dominated_by.get(idx_first_point, 0) + 1
                dominates[idx_second_point].append(idx_first_point)
        
    #sorted_dict = dict(sorted(my_dict.items(), key=lambda item: item[1]))

    curr_level = 0
    while len(is_dominated_by) > 0:
  
        non_dominated_indices = [idx for idx, dominance_count in is_dominated_by.items() if dominance_count == 0]
        for idx in non_dominated_indices:
            
            for dominated_idx in dominates[idx]:
                is_dominated_by[dominated_idx] -= 1
                
            levels[idx] = curr_level
            del is_dominated_by[idx]
        curr_level+=1
        
    return levels
    

In [ ]:
def get_fitness:
    

# Initial population

In [28]:
def solve(n, pCrossover, pMutation):
    #read csv
    filename = 'wine.csv'  
    df = pd.read_csv(filename)
    num_features = df.shape[1] -1
    
    #generate p0
    p0 = np.random.randint(2, size=(n, num_features))
    print(p0)
    print(p0[1][0],p0[1][1],p0[1][2])


# test functions

In [29]:
solve(10,0.5,0.5)

[[1 1 1 0 0 0 1 0 0 0 0]
 [0 0 0 1 1 0 1 1 1 0 1]
 [0 1 0 0 1 0 1 0 0 1 1]
 [1 0 1 0 1 1 0 1 0 0 0]
 [1 0 1 1 1 1 1 1 0 0 0]
 [1 0 1 0 1 1 0 1 0 1 0]
 [1 1 0 1 1 1 1 1 0 1 1]
 [0 1 0 1 1 1 0 0 0 0 0]
 [1 0 0 1 1 1 1 1 1 0 0]
 [0 1 0 1 1 0 0 1 0 1 1]]
0 0 0


In [15]:
def test_NSGA():
    fitn = [
        [1,2],
        [5,3],
        [6,5],
        [4,2],
        [2,4],
        [3.88,4.14],
        [3,3],
        [2,1]    
    ]

    levels = NSGA2(fitn)
    print(levels)